//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontentCompartido.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idioma
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontentCompartido.Resources.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tienda Virtual.
        /// </summary>
        internal static string NombreAplicacion
        {
            get
            {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar
        {
            get
            {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        internal static string Tienda
        {
            get
            {
                return ResourceManager.GetString("Tienda", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        internal static string Categorias
        {
            get
            {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        internal static string Productos
        {
            get
            {
                return ResourceManager.GetString("Productos", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Contacto
        {
            get
            {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }




        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Carrito
        {
            get
            {
                return ResourceManager.GetString("Carrito", resourceCulture);
            }
        }



        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Total
        {
            get
            {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }



        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Cerrar
        {
            get
            {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }



        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Comprar
        {
            get
            {
                return ResourceManager.GetString("Comprar", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string Nuevo
        {
            get
            {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }


        /// <summary>
        ///   Busca una cadena traducida similar a Añadir al Carrito.
        /// </summary>
        internal static string AgregarAlCarrito
        {
            get
            {
                return ResourceManager.GetString("AgregarAlCarrito", resourceCulture);
            }
        }

    }
}
